### ISSUE TITLE
Open A Unity Forum Thread

### ISSUE THREAD

**Issue by stctn** [simeonradivoev/UniGit#11]
I just saw this:
![unigit](https://user-images.githubusercontent.com/21353964/28140555-683a1bd6-6761-11e7-9ca6-f8adbe7ce3c8.PNG)

I suggest you open a Unity forum thread. This way, you can use the community as a massive tester group. It will also be easier for you to communicate with the users.

Also, don't forget to put the thread link to the description in asset store page.

**Comment by simeonradivoev** [comment]
I do have a [forum post](https://forum.unity3d.com/threads/opensource-unigit-in-editor-git-gui.440646/), but I didn't think to link it in the asset store or the readme file.

**Comment by stctn** [comment]
Cross-linking is essential. You need to connect places where people can discover the product.
