### ISSUE TITLE
Sytem.DllNotFoundException

### ISSUE THREAD

**Issue by JeromeJ** [simeonradivoev/UniGit#18]
Oddly, the error shows path that doesn't exist on my machine, are they yours?

![System.DllNotFoundException](https://user-images.githubusercontent.com/650065/34917890-7e4d24cc-f94c-11e7-80b4-e2d29028bf00.png)
![DllNotFoundException](https://user-images.githubusercontent.com/650065/34917891-7e6633f4-f94c-11e7-829d-7e039338fb6c.png)

I'm using 2017.3.0f3 under Win10.
What DLL am I missing? Could it be embarked within your asset?

**Comment by JeromeJ** [comment]
I saw you wrote "As for the dll errors they just telling you that the old version of gitlib2 are missing during recompile, because when you update unity loads the old versions of uniGit before the new ones recompile. These errors are nothing to worry about and they can't really be avoided." but I just made a fresh installation. Will those errors only pop up once?

**Comment by simeonradivoev** [comment]
These paths are the same for all, it's just a path on the machine that unity was built on I presume.

As for this error only just showing once, I would guess so. Try and restarting the editor and see.
