### ISSUE TITLE
NullReferenceException when opening the UniGit menu

### ISSUE THREAD

**Issue by JeromeJ** [simeonradivoev/UniGit#19]
I get this error whenever I open the UniGit menu.

NullReferenceException: Object reference not set to an instance of an object
UniGit.GitUnityMenu.InitilizeValidate ()

**Comment by JeromeJ** [comment]
Initialize is also grayed out. (And the help window, all glitchy :))

**Comment by simeonradivoev** [comment]
Is it connected to your other issue #18 ? I think you need to restart the Unity Editor. I don't have enough experience with that kind of error to write anything in the documentation.
If in case it's not connected to that issue, can you post the full error log when you open the menu ?

**Comment by JeromeJ** [comment]
Ah, it seems it actually is. Good call. Upon restarting, the System.DllNotfoundException cleared and the menu isn't bugged out anymore.

I was still unable to Initialize from the UniGit menu but I'm pretty sure it was because I didn't import it in a fresh project. It works fine on a bland new project. (Except for that pesky first run)

(As for full logs, there was nothing else except the annoying `<RI.Hid> Failed to create device file:
 2 The system cannot find the file specified.` that apparently lot of people have been having lately - but I don't think it's related)

**Comment by simeonradivoev** [comment]
Hm, strange. You should be able to initialize a repository if don't have one already.

**Comment by simeonradivoev** [comment]
I fixed the initialization option in the latest version.
