### ISSUE TITLE
AmbiguousSpecificationException when accessing Git context menu on folders

### ISSUE THREAD

**Issue by JeromeJ** [simeonradivoev/UniGit#20]
I get an `AmbiguousSpecificationException` when accessing Git context menu on folders.

![screenshot 16](https://user-images.githubusercontent.com/650065/34933564-9af4489a-f9d7-11e7-82d0-30f7fcc713dd.png)
![screenshot 17](https://user-images.githubusercontent.com/650065/34933565-9b532b26-f9d7-11e7-964c-ade0a71d6d9b.png)

Third screenshot shows how I did manage to add a directory nonetheless but its icon is wrong. (It also shows up in the Git diff window). I'm not sure but I think the issue is related.

![screenshot 19](https://user-images.githubusercontent.com/650065/34933692-183ec2e4-f9d8-11e7-9e94-8393f3fdcea9.png)

```
AmbiguousSpecificationException: More than one file matches the pathspec 'Assets\Plugins\LibGit2Sharp'. You can either force a literal path evaluation (GIT_STATUS_OPT_DISABLE_PATHSPEC_MATCH), or use git_status_foreach().
LibGit2Sharp.Core.Proxy.git_status_file (LibGit2Sharp.Core.Handles.RepositorySafeHandle repo, LibGit2Sharp.Core.FilePath path)
LibGit2Sharp.Repository.RetrieveStatus (System.String filePath)
UniGit.GitProjectContextMenus+<>c.<AddSelectedValidate>b__4_1 (System.String g)
System.Linq.Enumerable.Any[String] (IEnumerable`1 source, System.Func`2 predicate)
UniGit.GitProjectContextMenus.AddSelectedValidate ()
```

and

```
AmbiguousSpecificationException: More than one file matches the pathspec 'Assets\Plugins\LibGit2Sharp'. You can either force a literal path evaluation (GIT_STATUS_OPT_DISABLE_PATHSPEC_MATCH), or use git_status_foreach().
LibGit2Sharp.Core.Proxy.git_status_file (LibGit2Sharp.Core.Handles.RepositorySafeHandle repo, LibGit2Sharp.Core.FilePath path)
LibGit2Sharp.Repository.RetrieveStatus (System.String filePath)
UniGit.GitProjectContextMenus+<>c.<RemoveSelectedValidate>b__6_1 (System.String g)
System.Linq.Enumerable.Any[String] (IEnumerable`1 source, System.Func`2 predicate)
UniGit.GitProjectContextMenus.RemoveSelectedValidate ()

```

**Comment by simeonradivoev** [comment]
It has to do with the fact that Git doesn't know what folders are. Git doesn't handle paths, but unity uses .meta files for paths. I will have to look how to get rid of these errors.
Btw do you have show empty folders enabled in the UniGit settings ?

**Comment by JeromeJ** [comment]
I hadn't (does it matter?), but all my folders are populated with `.gitkeep` just in case.
