### ISSUE TITLE
"recursive OnGUI rendering, or the previous OnGUI did not clean up properly"

### ISSUE THREAD

**Issue by haywirephoenix** [simeonradivoev/UniGit#22]
UniGit is so cool. Everything seems to work except I get this error message:

"GUI Window tried to begin rendering while something else had not finished rendering! Either you have a recursive OnGUI rendering, or the previous OnGUI did not clean up properly."

Potential conflict with Script Inspector.

Thanks!

**Comment by haywirephoenix** [comment]
Update:  Error occurs when dragging UniGit tabs, and seems to be fixed by disabling Lazy Update Mode

**Comment by simeonradivoev** [comment]
Yes I fixed that, I just haven't published it yet.
