### ISSUE TITLE
Bugs with "Diff Inspector"

### ISSUE THREAD

**Issue by Doviskaune** [simeonradivoev/UniGit#24]
Modified file - two same line indexes "11":
![image](https://user-images.githubusercontent.com/21333672/35639619-7892fe92-06c3-11e8-9ed8-b6aae9ecea25.png)

"Difference with previous version"- files are swaped, line 11 missing:
![image](https://user-images.githubusercontent.com/21333672/35639734-cdbe0998-06c3-11e8-93c8-ad7b3d2801e4.png)
(image of the same commit)
Opened with Tortoise Git:
![image](https://user-images.githubusercontent.com/21333672/35640070-ccf0abbe-06c4-11e8-9ed2-eda5a42174b8.png)

**Comment by simeonradivoev** [comment]
Yea I had some problems with it too. It did make a fix, hopefully it solves such problems. I will close the issue once 1.3 is out
