### ISSUE TITLE
DllNotFoundException: libgit2 at every frames

### ISSUE THREAD

**Issue by JeromeJ** [simeonradivoev/UniGit#25]
> DllNotFoundException: libgit2
LibGit2Sharp.Core.NativeMethods+LibraryLifetimeObject..ctor () (at D:/My Documents/My Pictures/My Art/Games/UniGit-GitLib2SharpSource/Assets/Plugins/LibGit2SharpSource/Core/NativeMethods.cs:32)
LibGit2Sharp.Core.NativeMethods..cctor () (at D:/My Documents/My Pictures/My Art/Games/UniGit-GitLib2SharpSource/Assets/Plugins/LibGit2SharpSource/Core/NativeMethods.cs:79)
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for LibGit2Sharp.Core.NativeMethods
LibGit2Sharp.Core.Handles.SafeHandleBase..ctor () (at D:/My Documents/My Pictures/My Art/Games/UniGit-GitLib2SharpSource/Assets/Plugins/LibGit2SharpSource/Core/Handles/SafeHandleBase.cs:103)
LibGit2Sharp.Core.Handles.NullRepositorySafeHandle..ctor () (at D:/My Documents/My Pictures/My Art/Games/UniGit-GitLib2SharpSource/Assets/Plugins/LibGit2SharpSource/Core/Handles/NullRepositorySafeHandle.cs:7)
LibGit2Sharp.Core.Proxy.git_repository_open_ext (System.String path, RepositoryOpenFlags flags, System.String ceilingDirs) (at D:/My Documents/My Pictures/My Art/Games/UniGit-GitLib2SharpSource/Assets/Plugins/LibGit2SharpSource/Core/Proxy.cs:2527)
LibGit2Sharp.Repository.IsValid (System.String path) (at D:/My Documents/My Pictures/My Art/Games/UniGit-GitLib2SharpSource/Assets/Plugins/LibGit2SharpSource/Repository.cs:168)
UniGit.GitInitializer.get_IsValidRepo () (at D:/My Documents/My Pictures/My Art/Games/UniGit/Assets/Plugins/UniGit/Editor/GitInitializer.cs:69)
UniGit.GitFileWatcher..ctor (System.String repoPath, UniGit.GitManager gitManager, UniGit.GitCallbacks gitCallbacks, UniGit.GitSettingsJson gitSettings, UniGit.GitInitializer initializer, Boolean trackAssetsPath) (at D:/My Documents/My Pictures/My Art/Games/UniGit/Assets/Plugins/UniGit/Editor/GitFileWatcher.cs:39)
System.Reflection.MonoCMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:513)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoCMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:519)
System.Reflection.MonoCMethod.Invoke (BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:528)
System.Reflection.ConstructorInfo.Invoke (System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/ConstructorInfo.cs:77)
UniGit.Utils.InjectionHelper.CreateInstance (System.Type type, System.Object[] additionalArguments) (at D:/My Documents/My Pictures/My Art/Games/UniGit/Assets/Plugins/UniGit/Editor/Utils/InjectionHelper.cs:83)
UniGit.Utils.InjectionHelper+Resolve.EnsureInstance (UniGit.Utils.InjectionHelper injectionHelper) (at D:/My Documents/My Pictures/My Art/Games/UniGit/Assets/Plugins/UniGit/Editor/Utils/InjectionHelper.cs:528)
UniGit.Utils.InjectionHelper.CreateNonLazy () (at D:/My Documents/My Pictures/My Art/Games/UniGit/Assets/Plugins/UniGit/Editor/Utils/InjectionHelper.cs:353)
UniGit.UniGitLoader.Rebuild (UniGit.Utils.InjectionHelper injectionHelper) (at D:/My Documents/My Pictures/My Art/Games/UniGit/Assets/Plugins/UniGit/Editor/UniGitLoader.cs:100)
UniGit.UniGitLoader..cctor () (at D:/My Documents/My Pictures/My Art/Games/UniGit/Assets/Plugins/UniGit/Editor/UniGitLoader.cs:71)
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for UniGit.UniGitLoader
System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor (RuntimeTypeHandle type) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Runtime.CompilerServices/RuntimeHelpers.cs:101)
UnityEditor.EditorAssemblies.ProcessEditorInitializeOnLoad (System.Type type) (at C:/buildslave/unity/build/Editor/Mono/EditorAssemblies.cs:136)

Asset unusable as is, sadly.
Do note that the path aren't mine (presumably yours, is that where the issue come from?).

**Comment by JeromeJ** [comment]
Came back on my previous, somewhat related issue and closing and reopening Unity fixes it.
Still pushed the issue since it was a slightly different one with another behavior. Oh so very odd.

**Comment by simeonradivoev** [comment]
The path is just debug info, it's not the problem. When did the problem occur ? Was it after updating?

**Comment by JeromeJ** [comment]
Clean install from the asset store.

**Comment by simeonradivoev** [comment]
I just tested it out and I get the same thing. Damn you Unity.
