### ISSUE TITLE
FindObjectsOfTypeAll can only be called from the main thread.

### ISSUE THREAD

**Issue by starikcetin** [simeonradivoev/UniGit#28]
Getting the error on the title periodically on a fresh clone of this repo.

**Comment by simeonradivoev** [comment]
UniGit version I mean. You can find it in the menu `UniGit/About`

**Comment by starikcetin** [comment]
The latest release, 1.4.1

**Comment by simeonradivoev** [comment]
Fixed in 6fd08edd6a2b514b7251c98cd2f2b32d9ae21f42

**Comment by starikcetin** [comment]
Awesome. I will try it out when I am available.
