### ISSUE TITLE
Branch Creation

### ISSUE THREAD

**Issue by simeonradivoev** [simeonradivoev/UniGit#3]
Add Native support for branch creation.
_This can be done using external tools_

**Comment by Shadowblitz16** [comment]
@simeonradivoev is there more info on this? I currently cannot find a way to create a branch.

**Comment by simeonradivoev** [comment]
Check https://github.com/simeonradivoev/UniGit/wiki/Branches

**Comment by Shadowblitz16** [comment]
ok thankyou :>
