### ISSUE TITLE
What version of libgit2 do you use?

### ISSUE THREAD

**Issue by jorgeamado** [simeonradivoev/UniGit#34]
I've found that the latest libgit2sharp crashes Unity. 
Did you make something with original libgit2 dll to avoid crash? 
@simeonradivoev

**Comment by simeonradivoev** [comment]
I don't remember the exact version the dll should say, but I did modify the source code to remove .net 3.5+ parts.

**Comment by simeonradivoev** [comment]
Ah yes I remember now it's in the LibGit2SharpSource branch.

**Comment by jorgeamado** [comment]
Did you managed how to fix crashes?

**Comment by simeonradivoev** [comment]
I believe so. I just put the source code in unity. That a good way to check if it compiles. Then you can just grab the generated .dll by Unity.
