### ISSUE TITLE
NullReference (wrong path?) on Unity 2020.2.2f1

### ISSUE THREAD

**Issue by Archaoss** [simeonradivoev/UniGit#40]
After importing package in project in Unity (2020.2.2f1).
There is no drive `D:` on my system.

> NullReferenceException: Object reference not set to an instance of an object
> UniGit.Utils.GitReflectionHelper..ctor () (at D:/My Documents/My Pictures/My Art/Games/UniGit/Assets/Plugins/UniGit/Editor/Utils/GitReflectionHelper.cs:16)
> System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) (at <9577ac7a62ef43179789031239ba8798>:0)
> Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
> System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) (at <9577ac7a62ef43179789031239ba8798>:0)
> System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) (at <9577ac7a62ef43179789031239ba8798>:0)
> System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) (at <9577ac7a62ef43179789031239ba8798>:0)
> System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) (at <9577ac7a62ef43179789031239ba8798>:0)
> System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) (at <9577ac7a62ef43179789031239ba8798>:0)
> System.Activator.CreateInstance (System.Type type) (at <9577ac7a62ef43179789031239ba8798>:0)
> UniGit.Utils.InjectionHelper.CreateInstance (System.Type type, System.Object[] additionalArguments) (at D:/My Documents/My Pictures/My Art/Games/UniGit/Assets/Plugins/UniGit/Editor/Utils/InjectionHelper.cs:87)
> UniGit.Utils.InjectionHelper+Resolve.CreateInstance (UniGit.Utils.InjectionHelper injectionHelper) (at D:/My Documents/My Pictures/My Art/Games/UniGit/Assets/Plugins/UniGit/Editor/Utils/InjectionHelper.cs:545)
> UniGit.Utils.InjectionHelper+Resolve.EnsureInstance (UniGit.Utils.InjectionHelper injectionHelper) (at D:/My Documents/My Pictures/My Art/Games/UniGit/Assets/Plugins/UniGit/Editor/Utils/InjectionHelper.cs:552)
> UniGit.Utils.InjectionHelper+Resolve.GetInstance (UniGit.Utils.InjectionHelper injectionHelper) (at D:/My Documents/My Pictures/My Art/Games/UniGit/Assets/Plugins/UniGit/Editor/Utils/InjectionHelper.cs:529)
> UniGit.Utils.InjectionHelper.GetInstance[T] () (at D:/My Documents/My Pictures/My Art/Games/UniGit/Assets/Plugins/UniGit/Editor/Utils/InjectionHelper.cs:314)
> UniGit.UniGitLoader.Rebuild (UniGit.Utils.InjectionHelper injectionHelper) (at D:/My Documents/My Pictures/My Art/Games/UniGit/Assets/Plugins/UniGit/Editor/UniGitLoader.cs:105)
> UniGit.UniGitLoader..cctor () (at D:/My Documents/My Pictures/My Art/Games/UniGit/Assets/Plugins/UniGit/Editor/UniGitLoader.cs:82)
> Rethrow as TypeInitializationException: The type initializer for 'UniGit.UniGitLoader' threw an exception.
> UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at <433cbae83977409887e43d50043210d2>:0)

**Comment by simeonradivoev** [comment]
It hasn't been tested on unity 2020 yet. Probably an issue with a missing unity member that was only accessible by reflection before.

**Comment by simeonradivoev** [comment]
Are you using the latest version from GitHub using the package manager?

**Comment by danvim** [comment]
Same issue on 2021.2.11f

> NullReferenceException: Object reference not set to an instance of an object
UniGit.Utils.GitReflectionHelper..ctor () (at D:/My Documents/My Pictures/My Art/Games/UniGit/Assets/Plugins/UniGit/Editor/Utils/GitReflectionHelper.cs:16)

I don't have this path.
