### ISSUE TITLE
How to Install in Unity 2018.4.20 & 2017.4.28

### ISSUE THREAD

**Issue by borrougagnou** [simeonradivoev/UniGit#47]
Hello !
I need a help, I tried to add github repository into Unity 2018.4.20f1 but there's no "Import from git" in package manager or something like that
and when I try to add git in manifest.json I obtain error "Failed to resolve package"

so, yeah, I looking for how to install and use UniGit into my project.

Thank you for your help !

**Comment by simeonradivoev** [comment]
The Installation in the [readme file](https://github.com/simeonradivoev/UniGit#installation) explains how to add it to the manifest file.

**Comment by borrougagnou** [comment]
Hello, sorry for reopen this issue,
at first I understand my problem,
I don't have installed "git" into my computer and forgot "," at the end of the json file,
now it's fixed.

now I have another problem, maybe I do something wrong ?
after I import the package into an empty unity project, I have 256 error:
![image](https://user-images.githubusercontent.com/10796546/119061856-4a140080-ba10-11eb-918a-dc19c86a5209.png)
![image](https://user-images.githubusercontent.com/10796546/119061879-5b5d0d00-ba10-11eb-8844-888af4b9339c.png)
![image](https://user-images.githubusercontent.com/10796546/119061894-66b03880-ba10-11eb-8b89-c6dca0a6345b.png)
[...]
[latest]
![image](https://user-images.githubusercontent.com/10796546/119061912-73cd2780-ba10-11eb-893e-d55508bd1fc0.png)

my folder is like:
```
.git
Assets
Library
Logs
Packages
ProjectSettings
Temp
.gitignore
README.md
```


and also another thing I discover,
when I try to migrate project from Unity 2017.4 to 2018.4 (with Unity Hub)
he say your script is incompatible to migrate.

Thank you for your help.

**Comment by simeonradivoev** [comment]
I have no idea what is going on in here. The latest version could be incompatible with the older version of unity. Maybe try an older version of the plugin.
Another thing you can try is changing the [Scripting Runtime version](https://docs.unity3d.com/2018.3/Documentation/Manual/ScriptingRuntimeUpgrade.html) to 4.x

**Comment by borrougagnou** [comment]
Hello, Unfortunately your method didn't work....
so I downloaded the "Asset Store version" and I obtain that when I try to pull:
![image](https://user-images.githubusercontent.com/10796546/119166115-8a01d480-ba5e-11eb-848f-63bfe2394b22.png)

I don't know what he mean by "unsuported protocol"...

**Comment by simeonradivoev** [comment]
What is the URL of the repository. Only HTTP/S is supported.

**Comment by borrougagnou** [comment]
the url of the repository is the ssh mode "git@something.com/user/repo"

also yeah, it work in "http" mode, really really slow but it work !

Thanks

**Comment by borrougagnou** [comment]
ha ok,
personally I use SSH mode, so (git@IP:port/user/repo) maybe that"s why
also, I tried HTTP, it work, but the program is really really slow in diff... same with the 'gitignore'
