### ISSUE TITLE
Extrange Route

### ISSUE THREAD

**Issue by ajbalmon** [simeonradivoev/UniGit#7]
I just installed version 1.0.7
Once I have configured the repository, when I make "fetch" I get the following error:

NullReferenceException: Object reference not set to an instance of an object
UniGit.GitHistoryWindow.DoToolbar (Rect rect, LibGit2Sharp.RepositoryInformation info) (at D:/My Documents/My Pictures/My Art/Games/UniGit/Assets/Plugins/UniGit/Editor/GitHistoryWindow.cs:318)
UniGit.GitHistoryWindow.OnGUI () (at D:/My Documents/My Pictures/My Art/Games/UniGit/Assets/Plugins/UniGit/Editor/GitHistoryWindow.cs:266)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)

I have Unity installed on a drive other than C.

**Comment by simeonradivoev** [comment]
Did you set up the remote for your branch ?
