### ISSUE TITLE
nullreff error

### ISSUE THREAD

**Issue by UncleJey** [simeonradivoev/UniGit#9]
Hi again!
Now win10, Unity3d 5.5.3 x64

trying pull repo. 

NullReferenceException: Object reference not set to an instance of an object
UniGit.GitWizardBase.Init (LibGit2Sharp.Branch branch) (at D:/My Documents/My Pictures/My Art/Games/UniGit/Assets/Plugins/UniGit/Editor/GitWizardBase.cs:42)
UniGit.GitHistoryWindow.DoToolbar (Rect rect, LibGit2Sharp.RepositoryInformation info) (at D:/My Documents/My Pictures/My Art/Games/UniGit/Assets/Plugins/UniGit/Editor/GitHistoryWindow.cs:311)
UniGit.GitHistoryWindow.OnGUI () (at D:/My Documents/My Pictures/My Art/Games/UniGit/Assets/Plugins/UniGit/Editor/GitHistoryWindow.cs:266)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)

**Comment by simeonradivoev** [comment]
Have you setup remotes for your branch ?

**Comment by UncleJey** [comment]
yes. 
remote and credentials.

**Comment by simeonradivoev** [comment]
Have you made a commit ? I fixed it but if you can't wait for a build, you should have at least one commit.

**Comment by simeonradivoev** [comment]
Also if you are trying to clone a repository inside the editor that won't work. You will have to do it from outside.
